name: Rain Monitor

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  rain-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests yagmail tenacity
        
    - name: Create logs directory
      run: mkdir -p logs
        
    - name: Run rain monitor
      run: python rain_monitor.py
      
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      if: always()  # Upload logs even if the script fails
      with:
        name: rain-monitor-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30